language: go
services:
  - docker
env:
  - GO111MODULE=on
go:
  - "1.11.x"
git:
  depth: 1

jobs:
  include:
    - stage: "build"
      name: "Build"
      script:
        - go build -o deckhand
    - stage: deploy
      install: skip
      name: "Deploying docker image"
      script:
        - echo "Logging into Docker"
        - docker login -u=$DOCKER_USER -p=$DOCKER_PASS quay.io
        - docker build -t deckhand .
        - builds/deploy.sh


stages:
  - build
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request
