language: go
services:
  - docker
env:
  - GO111MODULE=on
go:
  - "1.11.x"
git:
  depth: 1

jobs:
  include:
    - stage: "build"
      name: "Build"
      script:
        - go build -o deckhand
    - stage: deploy
      install: skip
      name: "Deploying docker image"
      script: skip
      deploy:
        provider: script
        script:
          - echo "Logging into Docker"
          - docker login -u=$DOCKER_USER -p=$DOCKER_PASS quay.io
          - docker build -t deckhand .
          - docker tag deckhand quay.io/nfons/deckhand:$TRAVIS_BRANCH
          - docker push quay.io/nfons/deckhand:$TRAVIS_BRANCH
        skip_cleanup: true
        on:
          tags: true
          branch: master
          
       

stages:
  - install
  - build
  - name: deploy

