apiVersion: apps/v1
kind: Deployment
metadata:
  name: deckhand
  labels:
    app: deckhand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deckhand
  template:
    metadata:
      labels:
        app: deckhand
    spec:
      containers:
        - name: deckhand
          image: quay.io/nfons/deckhand
          ports:
            - containerPort: 8080
          env:
            - name: DECK_GIT_REPO
              value: https://github.nike.com/zodiacmetrics/gitOps.git
            - name: DECK_GIT_USER
              value: nfons2 # Need to get a dummy one for this later
            - name: DECK_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: github-access-token
                  key: accessToken
            - name: DECK_CLUSTER_NAME
              value: dev
